username: sngndncmn
password: coffee

application_name: HealthCare Insight&copy;

issuu_key: "7epzck3p0csmgo3yo7kpfwwebwnuwxs4"
issuu_secret: "m82b78tie0336wqffajbhrwedgatejlw"

job_posting_link: "http://www.veriskhealth.com/content/careers"

free_trial_landing_page: "http://www2.hcinsight.com/l/1492/2009-12-21/G23NR"